#pragma once

#if defined(STM32F40_41xxx) || defined(STM32F411xE)
//-----------------------PORTS A GROUP--------------------------//
#define PA0             GPIOPinID(PORTA,0)
#define PA1             GPIOPinID(PORTA,1)
#define PA2             GPIOPinID(PORTA,2)
#define PA3             GPIOPinID(PORTA,3)
#define PA4             GPIOPinID(PORTA,4)
#define PA5             GPIOPinID(PORTA,5)
#define PA6             GPIOPinID(PORTA,6)
#define PA7             GPIOPinID(PORTA,7)
#define PA8             GPIOPinID(PORTA,8)
#define PA9             GPIOPinID(PORTA,9)
#define PA10            GPIOPinID(PORTA,10)
#define PA13            GPIOPinID(PORTA,13)
#define PA14            GPIOPinID(PORTA,14)
#define PA15            GPIOPinID(PORTA,15)
//-----------------------PORTS B GROUP--------------------------//
#define PB0             GPIOPinID(PORTB,0)
#define PB1             GPIOPinID(PORTB,1)
#define PB2             GPIOPinID(PORTB,2)
#define PB3             GPIOPinID(PORTB,3)
#define PB4             GPIOPinID(PORTB,4)
#define PB5             GPIOPinID(PORTB,5)
#define PB6             GPIOPinID(PORTB,6)
#define PB7             GPIOPinID(PORTB,7)
#define PB8             GPIOPinID(PORTB,8)
#define PB9             GPIOPinID(PORTB,9)
#define PB10            GPIOPinID(PORTB,10)
#define PB11            GPIOPinID(PORTB,11)
#define PB12            GPIOPinID(PORTB,12)
#define PB13            GPIOPinID(PORTB,13)
#define PB14            GPIOPinID(PORTB,14)
#define PB15            GPIOPinID(PORTB,15)
//-----------------------PORTS C GROUP--------------------------//
#define PC0             GPIOPinID(PORTC,0)
#define PC1             GPIOPinID(PORTC,1)
#define PC2             GPIOPinID(PORTC,2)
#define PC3             GPIOPinID(PORTC,3)
#define PC6             GPIOPinID(PORTC,6)
#define PC7             GPIOPinID(PORTC,7)
#define PC8             GPIOPinID(PORTC,8)
#define PC9             GPIOPinID(PORTC,9)
#define PC10            GPIOPinID(PORTC,10)
#define PC11            GPIOPinID(PORTC,11)
#define PC12            GPIOPinID(PORTC,12)
#define PC13            GPIOPinID(PORTC,13)
#define PC14            GPIOPinID(PORTC,14)
#define PC15            GPIOPinID(PORTC,15)
//-----------------------PORTS D GROUP--------------------------//
#define PD0             GPIOPinID(PORTD,0)
#define PD1             GPIOPinID(PORTD,1)
#define PD2             GPIOPinID(PORTD,2)
#define PD3             GPIOPinID(PORTD,3)
#define PD4             GPIOPinID(PORTD,4)
#define PD5             GPIOPinID(PORTD,5)
#define PD6             GPIOPinID(PORTD,6)
#define PD7             GPIOPinID(PORTD,7)
#define PD8             GPIOPinID(PORTD,8)
#define PD9             GPIOPinID(PORTD,9)
#define PD10            GPIOPinID(PORTD,10)
#define PD11            GPIOPinID(PORTD,11)
#define PD12            GPIOPinID(PORTD,12)
#define PD13            GPIOPinID(PORTD,13)
#define PD14            GPIOPinID(PORTD,14)
#define PD15            GPIOPinID(PORTD,15)
//-----------------------PORTS E GROUP--------------------------//
#define PE0             GPIOPinID(PORTE,0)
#define PE1             GPIOPinID(PORTE,1)
#define PE2             GPIOPinID(PORTE,2)
#define PE3             GPIOPinID(PORTE,3)
#define PE4             GPIOPinID(PORTE,4)
#define PE5             GPIOPinID(PORTE,5)
#define PE6             GPIOPinID(PORTE,6)
#define PE7             GPIOPinID(PORTE,7)
#define PE8             GPIOPinID(PORTE,8)
#define PE9             GPIOPinID(PORTE,9)
#define PE10            GPIOPinID(PORTE,10)
#define PE11            GPIOPinID(PORTE,11)
#define PE12            GPIOPinID(PORTE,12)
#define PE13            GPIOPinID(PORTE,13)
#define PE14            GPIOPinID(PORTE,14)
#define PE15            GPIOPinID(PORTE,15)
//-----------------------COUNTERS------------------------------//
#define TIM1_CNT        ((uint32_t *)&(TIM1->CNT))
#define TIM2_CNT        ((uint32_t *)&(TIM2->CNT))
#define TIM3_CNT        ((uint32_t *)&(TIM3->CNT))
#define TIM4_CNT        ((uint32_t *)&(TIM4->CNT))
#define TIM5_CNT        ((uint32_t *)&(TIM5->CNT))
#define TIM6_CNT        ((uint32_t *)&(TIM6->CNT))
#define TIM7_CNT        ((uint32_t *)&(TIM7->CNT))
#define TIM8_CNT        ((uint32_t *)&(TIM8->CNT))
#define TIM9_CNT        ((uint32_t *)&(TIM9->CNT))
#define TIM10_CNT       ((uint32_t *)&(TIM10->CNT))
#define TIM11_CNT       ((uint32_t *)&(TIM11->CNT))
#define TIM12_CNT       ((uint32_t *)&(TIM12->CNT))
#define TIM13_CNT       ((uint32_t *)&(TIM13->CNT))
#define TIM14_CNT       ((uint32_t *)&(TIM14->CNT))
//-----------------------CHANNELS COMPARE----------------------//
#define TIM1_CCR1       ((uint32_t *)&(TIM1->CCR1))
#define TIM1_CCR2       ((uint32_t *)&(TIM1->CCR2))
#define TIM1_CCR3       ((uint32_t *)&(TIM1->CCR3))
#define TIM1_CCR4       ((uint32_t *)&(TIM1->CCR4))

#define TIM2_CCR1       ((uint32_t *)&(TIM2->CCR1))
#define TIM2_CCR2       ((uint32_t *)&(TIM2->CCR2))
#define TIM2_CCR3       ((uint32_t *)&(TIM2->CCR3))
#define TIM2_CCR4       ((uint32_t *)&(TIM2->CCR4))

#define TIM3_CCR1       ((uint32_t *)&(TIM3->CCR1))
#define TIM3_CCR2       ((uint32_t *)&(TIM3->CCR2))
#define TIM3_CCR3       ((uint32_t *)&(TIM3->CCR3))
#define TIM3_CCR4       ((uint32_t *)&(TIM3->CCR4))

#define TIM4_CCR1       ((uint32_t *)&(TIM4->CCR1))
#define TIM4_CCR2       ((uint32_t *)&(TIM4->CCR2))
#define TIM4_CCR3       ((uint32_t *)&(TIM4->CCR3))
#define TIM4_CCR4       ((uint32_t *)&(TIM4->CCR4))

#define TIM5_CCR1       ((uint32_t *)&(TIM5->CCR1))
#define TIM5_CCR2       ((uint32_t *)&(TIM5->CCR2))
#define TIM5_CCR3       ((uint32_t *)&(TIM5->CCR3))
#define TIM5_CCR4       ((uint32_t *)&(TIM5->CCR4))

#define TIM8_CCR1       ((uint32_t *)&(TIM8->CCR1))
#define TIM8_CCR2       ((uint32_t *)&(TIM8->CCR2))
#define TIM8_CCR3       ((uint32_t *)&(TIM8->CCR3))
#define TIM8_CCR4       ((uint32_t *)&(TIM8->CCR4))

#define TIM9_CCR1       ((uint32_t *)&(TIM9->CCR1))
#define TIM9_CCR2       ((uint32_t *)&(TIM9->CCR2))

#define TIM10_CCR1       ((uint32_t *)&(TIM10->CCR1))
#define TIM11_CCR1       ((uint32_t *)&(TIM11->CCR1))

#define TIM12_CCR1       ((uint32_t *)&(TIM12->CCR1))
#define TIM12_CCR2       ((uint32_t *)&(TIM12->CCR2))

#define TIM13_CCR1       ((uint32_t *)&(TIM13->CCR1))
#define TIM14_CCR1       ((uint32_t *)&(TIM14->CCR1))
#endif/*STM32F40_41xxx*/

#ifdef STM32F401xx
//-----------------------PORTS A GROUP--------------------------//
#define PA0             GPIOPinID(PORTA,0)
#define PA1             GPIOPinID(PORTA,1)
#define PA2             GPIOPinID(PORTA,2)
#define PA3             GPIOPinID(PORTA,3)
#define PA4             GPIOPinID(PORTA,4)
#define PA5             GPIOPinID(PORTA,5)
#define PA6             GPIOPinID(PORTA,6)
#define PA7             GPIOPinID(PORTA,7)
#define PA8             GPIOPinID(PORTA,8)
#define PA9             GPIOPinID(PORTA,9)
#define PA10            GPIOPinID(PORTA,10)
#define PA11            GPIOPinID(PORTA,11)
#define PA12            GPIOPinID(PORTA,12)
#define PA13            GPIOPinID(PORTA,13)
#define PA14            GPIOPinID(PORTA,14)
#define PA15            GPIOPinID(PORTA,15)
//-----------------------PORTS B GROUP--------------------------//
#define PB0             GPIOPinID(PORTB,0)
#define PB1             GPIOPinID(PORTB,1)
#define PB2             GPIOPinID(PORTB,2)
#define PB3             GPIOPinID(PORTB,3)
#define PB4             GPIOPinID(PORTB,4)
#define PB5             GPIOPinID(PORTB,5)
#define PB6             GPIOPinID(PORTB,6)
#define PB7             GPIOPinID(PORTB,7)
#define PB8             GPIOPinID(PORTB,8)
#define PB9             GPIOPinID(PORTB,9)
#define PB10            GPIOPinID(PORTB,10)
#define PB11            GPIOPinID(PORTB,11)
#define PB12            GPIOPinID(PORTB,12)
#define PB13            GPIOPinID(PORTB,13)
#define PB14            GPIOPinID(PORTB,14)
#define PB15            GPIOPinID(PORTB,15)
//-----------------------PORTS C GROUP--------------------------//
#define PC15            GPIOPinID(PORTC,15)
#define PC14            GPIOPinID(PORTC,14)
#define PC13            GPIOPinID(PORTC,13)
//-----------------------COUNTERS------------------------------//
#define TIM1_CNT        ((uint32_t *)&(TIM1->CNT))
#define TIM2_CNT        ((uint32_t *)&(TIM2->CNT))
#define TIM3_CNT        ((uint32_t *)&(TIM3->CNT))
#define TIM4_CNT        ((uint32_t *)&(TIM4->CNT))
#define TIM5_CNT        ((uint32_t *)&(TIM5->CNT))
#define TIM9_CNT        ((uint32_t *)&(TIM9->CNT))
#define TIM10_CNT       ((uint32_t *)&(TIM10->CNT))
#define TIM11_CNT       ((uint32_t *)&(TIM11->CNT))
//-----------------------CHANNELS COMPARE----------------------//
#define TIM1_CCR1       ((uint32_t *)&(TIM1->CCR1))
#define TIM1_CCR2       ((uint32_t *)&(TIM1->CCR2))
#define TIM1_CCR3       ((uint32_t *)&(TIM1->CCR3))
#define TIM1_CCR4       ((uint32_t *)&(TIM1->CCR4))

#define TIM2_CCR1       ((uint32_t *)&(TIM2->CCR1))
#define TIM2_CCR2       ((uint32_t *)&(TIM2->CCR2))
#define TIM2_CCR3       ((uint32_t *)&(TIM2->CCR3))
#define TIM2_CCR4       ((uint32_t *)&(TIM2->CCR4))

#define TIM3_CCR1       ((uint32_t *)&(TIM3->CCR1))
#define TIM3_CCR2       ((uint32_t *)&(TIM3->CCR2))
#define TIM3_CCR3       ((uint32_t *)&(TIM3->CCR3))
#define TIM3_CCR4       ((uint32_t *)&(TIM3->CCR4))

#define TIM4_CCR1       ((uint32_t *)&(TIM4->CCR1))
#define TIM4_CCR2       ((uint32_t *)&(TIM4->CCR2))
#define TIM4_CCR3       ((uint32_t *)&(TIM4->CCR3))
#define TIM4_CCR4       ((uint32_t *)&(TIM4->CCR4))

#define TIM5_CCR1       ((uint32_t *)&(TIM5->CCR1))
#define TIM5_CCR2       ((uint32_t *)&(TIM5->CCR2))
#define TIM5_CCR3       ((uint32_t *)&(TIM5->CCR3))
#define TIM5_CCR4       ((uint32_t *)&(TIM5->CCR4))

#define TIM9_CCR1       ((uint32_t *)&(TIM9->CCR1))
#define TIM9_CCR2       ((uint32_t *)&(TIM9->CCR2))

#define TIM10_CCR1       ((uint32_t *)&(TIM10->CCR1))
#define TIM11_CCR1       ((uint32_t *)&(TIM11->CCR1))

#endif/*STM32F401xx*/
